// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Poulina.GestionCommentaire.Data.Context;

namespace Poulina.GestionCommentaire.Data.Migrations
{
    [DbContext(typeof(GestionCommContext))]
    [Migration("20200423211719_Times")]
    partial class Times
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Poulina.GestionCommentaire.Domain.Models.CatDemandeInfo", b =>
                {
                    b.Property<Guid>("IdCatDemande")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("IdCat");

                    b.Property<Guid>("IdDemandeInfo");

                    b.HasKey("IdCatDemande");

                    b.HasIndex("IdCat");

                    b.HasIndex("IdDemandeInfo");

                    b.ToTable("CatDemandeInfos");
                });

            modelBuilder.Entity("Poulina.GestionCommentaire.Domain.Models.Categorie", b =>
                {
                    b.Property<Guid>("IdCat")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Label");

                    b.HasKey("IdCat");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Poulina.GestionCommentaire.Domain.Models.CommDemandeInfo", b =>
                {
                    b.Property<Guid>("IdCommInfo")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("IdComm");

                    b.Property<Guid?>("IdDemandeInfo");

                    b.HasKey("IdCommInfo");

                    b.HasIndex("IdComm");

                    b.HasIndex("IdDemandeInfo");

                    b.ToTable("CommDemandeInfos");
                });

            modelBuilder.Entity("Poulina.GestionCommentaire.Domain.Models.CommVote", b =>
                {
                    b.Property<Guid>("IdCommVote")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("IdComm");

                    b.Property<Guid?>("IdVote");

                    b.HasKey("IdCommVote");

                    b.HasIndex("IdVote");

                    b.ToTable("CommVotes");
                });

            modelBuilder.Entity("Poulina.GestionCommentaire.Domain.Models.Commentaires", b =>
                {
                    b.Property<Guid>("IdComm")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.HasKey("IdComm");

                    b.ToTable("Commentaires");
                });

            modelBuilder.Entity("Poulina.GestionCommentaire.Domain.Models.DemandeInformation", b =>
                {
                    b.Property<Guid>("IdDemandeInfo")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.HasKey("IdDemandeInfo");

                    b.ToTable("DemandeInformation");
                });

            modelBuilder.Entity("Poulina.GestionCommentaire.Domain.Models.SousCategorie", b =>
                {
                    b.Property<Guid>("IdSousCate")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CatFK");

                    b.Property<string>("Label");

                    b.HasKey("IdSousCate");

                    b.HasIndex("CatFK");

                    b.ToTable("SousCategories");
                });

            modelBuilder.Entity("Poulina.GestionCommentaire.Domain.Models.Vote", b =>
                {
                    b.Property<Guid>("IdVote")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Note");

                    b.HasKey("IdVote");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("Poulina.GestionCommentaire.Domain.Models.CatDemandeInfo", b =>
                {
                    b.HasOne("Poulina.GestionCommentaire.Domain.Models.Categorie", "categories")
                        .WithMany("catDemandeInfos")
                        .HasForeignKey("IdCat");

                    b.HasOne("Poulina.GestionCommentaire.Domain.Models.DemandeInformation", "demandeInformations")
                        .WithMany("catDemandeInfos")
                        .HasForeignKey("IdDemandeInfo")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Poulina.GestionCommentaire.Domain.Models.CommDemandeInfo", b =>
                {
                    b.HasOne("Poulina.GestionCommentaire.Domain.Models.Commentaires", "commentaires")
                        .WithMany("commDemandeInfos")
                        .HasForeignKey("IdComm");

                    b.HasOne("Poulina.GestionCommentaire.Domain.Models.DemandeInformation", "demandeInformations")
                        .WithMany("commDemandeInfos")
                        .HasForeignKey("IdDemandeInfo");
                });

            modelBuilder.Entity("Poulina.GestionCommentaire.Domain.Models.CommVote", b =>
                {
                    b.HasOne("Poulina.GestionCommentaire.Domain.Models.Commentaires", "commentaires")
                        .WithMany("commVotes")
                        .HasForeignKey("IdVote");

                    b.HasOne("Poulina.GestionCommentaire.Domain.Models.Vote", "votes")
                        .WithMany("commVotes")
                        .HasForeignKey("IdVote");
                });

            modelBuilder.Entity("Poulina.GestionCommentaire.Domain.Models.SousCategorie", b =>
                {
                    b.HasOne("Poulina.GestionCommentaire.Domain.Models.Categorie", "Categories")
                        .WithMany("sousCategories")
                        .HasForeignKey("CatFK")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
