// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Poulina.GestionCommentaire.Data.Context;

namespace Poulina.GestionCommentaire.Data.Migrations
{
    [DbContext(typeof(GestionCommContext))]
    partial class GestionCommContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Poulina.GestionCommentaire.Domain.Models.CatDemandeInfo", b =>
                {
                    b.Property<Guid>("IdCatDemande")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdCat")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdDemandeInfo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActiveCatInfo")
                        .HasColumnType("bit");

                    b.HasKey("IdCatDemande");

                    b.HasIndex("IdCat");

                    b.HasIndex("IdDemandeInfo");

                    b.ToTable("CatDemandeInfos");
                });

            modelBuilder.Entity("Poulina.GestionCommentaire.Domain.Models.Categorie", b =>
                {
                    b.Property<Guid>("IdCat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActiveCat")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCat");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Poulina.GestionCommentaire.Domain.Models.CommVote", b =>
                {
                    b.Property<Guid>("IdCommVote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdComm")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdVote")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActiveCommVote")
                        .HasColumnType("bit");

                    b.HasKey("IdCommVote");

                    b.HasIndex("IdComm");

                    b.HasIndex("IdVote");

                    b.ToTable("CommVotes");
                });

            modelBuilder.Entity("Poulina.GestionCommentaire.Domain.Models.Commentaires", b =>
                {
                    b.Property<Guid>("IdComm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FkInfo")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FkMs")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActiveComm")
                        .HasColumnType("bit");

                    b.HasKey("IdComm");

                    b.HasIndex("FkInfo");

                    b.ToTable("Commentaires");
                });

            modelBuilder.Entity("Poulina.GestionCommentaire.Domain.Models.DemandeInformation", b =>
                {
                    b.Property<Guid>("IdDemandeInfo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("IdDomain")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActiveInfo")
                        .HasColumnType("bit");

                    b.Property<string>("Titre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDemandeInfo");

                    b.ToTable("DemandeInformation");
                });

            modelBuilder.Entity("Poulina.GestionCommentaire.Domain.Models.SousCategorie", b =>
                {
                    b.Property<Guid>("IdSousCate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CatFK")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActiveSousCat")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSousCate");

                    b.HasIndex("CatFK");

                    b.ToTable("SousCategories");
                });

            modelBuilder.Entity("Poulina.GestionCommentaire.Domain.Models.Vote", b =>
                {
                    b.Property<Guid>("IdVote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActiveVote")
                        .HasColumnType("bit");

                    b.Property<int>("Note")
                        .HasColumnType("int");

                    b.HasKey("IdVote");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("Poulina.GestionCommentaire.Domain.Models.CatDemandeInfo", b =>
                {
                    b.HasOne("Poulina.GestionCommentaire.Domain.Models.Categorie", "categories")
                        .WithMany("catDemandeInfos")
                        .HasForeignKey("IdCat");

                    b.HasOne("Poulina.GestionCommentaire.Domain.Models.DemandeInformation", "demandeInformations")
                        .WithMany("catDemandeInfos")
                        .HasForeignKey("IdDemandeInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("Poulina.GestionCommentaire.Domain.Models.CommVote", b =>
                {
                    b.HasOne("Poulina.GestionCommentaire.Domain.Models.Commentaires", "commentaires")
                        .WithMany("commVotes")
                        .HasForeignKey("IdComm");

                    b.HasOne("Poulina.GestionCommentaire.Domain.Models.Vote", "votes")
                        .WithMany("commVotes")
                        .HasForeignKey("IdVote");
                });

            modelBuilder.Entity("Poulina.GestionCommentaire.Domain.Models.Commentaires", b =>
                {
                    b.HasOne("Poulina.GestionCommentaire.Domain.Models.DemandeInformation", "demandeInformation")
                        .WithMany("commentaires")
                        .HasForeignKey("FkInfo");
                });

            modelBuilder.Entity("Poulina.GestionCommentaire.Domain.Models.SousCategorie", b =>
                {
                    b.HasOne("Poulina.GestionCommentaire.Domain.Models.Categorie", "Categories")
                        .WithMany("sousCategories")
                        .HasForeignKey("CatFK")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
